version: "3.8"
services:
  redis:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network:
    external: true