name: deploy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: meilisync-admin
          custom-args: --build-arg=GIT_TOKEN=${{ secrets.GIT_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy meilisync-admin
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment meilisync-admin
      - name: Deploy meilisync-admin-demo
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout restart deployment meilisync-admin-demo
